# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/eduar/Documents/GitHub/school/ece520l-system-on-chip-design-lab/axi_gpio_eg/axi_gpio_eg.srcs/sources_1/bd/axi_gpio_eg/ip/axi_gpio_eg_axi_gpio_2_0/axi_gpio_eg_axi_gpio_2_0.xci
# IP: The module: 'axi_gpio_eg_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eduar/Documents/GitHub/school/ece520l-system-on-chip-design-lab/axi_gpio_eg/axi_gpio_eg.gen/sources_1/bd/axi_gpio_eg/ip/axi_gpio_eg_axi_gpio_2_0/axi_gpio_eg_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_eg_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eduar/Documents/GitHub/school/ece520l-system-on-chip-design-lab/axi_gpio_eg/axi_gpio_eg.gen/sources_1/bd/axi_gpio_eg/ip/axi_gpio_eg_axi_gpio_2_0/axi_gpio_eg_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_eg_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eduar/Documents/GitHub/school/ece520l-system-on-chip-design-lab/axi_gpio_eg/axi_gpio_eg.gen/sources_1/bd/axi_gpio_eg/ip/axi_gpio_eg_axi_gpio_2_0/axi_gpio_eg_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_eg_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/eduar/Documents/GitHub/school/ece520l-system-on-chip-design-lab/axi_gpio_eg/axi_gpio_eg.srcs/sources_1/bd/axi_gpio_eg/ip/axi_gpio_eg_axi_gpio_2_0/axi_gpio_eg_axi_gpio_2_0.xci
# IP: The module: 'axi_gpio_eg_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/eduar/Documents/GitHub/school/ece520l-system-on-chip-design-lab/axi_gpio_eg/axi_gpio_eg.gen/sources_1/bd/axi_gpio_eg/ip/axi_gpio_eg_axi_gpio_2_0/axi_gpio_eg_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_eg_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eduar/Documents/GitHub/school/ece520l-system-on-chip-design-lab/axi_gpio_eg/axi_gpio_eg.gen/sources_1/bd/axi_gpio_eg/ip/axi_gpio_eg_axi_gpio_2_0/axi_gpio_eg_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_eg_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/eduar/Documents/GitHub/school/ece520l-system-on-chip-design-lab/axi_gpio_eg/axi_gpio_eg.gen/sources_1/bd/axi_gpio_eg/ip/axi_gpio_eg_axi_gpio_2_0/axi_gpio_eg_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_eg_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
