# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/axi_gpio_eg/axi_gpio_eg.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_eg || ORIG_REF_NAME==axi_gpio_eg} -quiet] -quiet

# IP: bd/axi_gpio_eg/ip/axi_gpio_eg_processing_system7_0_0/axi_gpio_eg_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_eg_processing_system7_0_0 || ORIG_REF_NAME==axi_gpio_eg_processing_system7_0_0} -quiet] -quiet

# IP: bd/axi_gpio_eg/ip/axi_gpio_eg_axi_gpio_0_0/axi_gpio_eg_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_eg_axi_gpio_0_0 || ORIG_REF_NAME==axi_gpio_eg_axi_gpio_0_0} -quiet] -quiet

# IP: bd/axi_gpio_eg/ip/axi_gpio_eg_ps7_0_axi_periph_1/axi_gpio_eg_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_eg_ps7_0_axi_periph_1 || ORIG_REF_NAME==axi_gpio_eg_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/axi_gpio_eg/ip/axi_gpio_eg_rst_ps7_0_50M_1/axi_gpio_eg_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_eg_rst_ps7_0_50M_1 || ORIG_REF_NAME==axi_gpio_eg_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/axi_gpio_eg/ip/axi_gpio_eg_xbar_0/axi_gpio_eg_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_eg_xbar_0 || ORIG_REF_NAME==axi_gpio_eg_xbar_0} -quiet] -quiet

# IP: bd/axi_gpio_eg/ip/axi_gpio_eg_auto_pc_0/axi_gpio_eg_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_eg_auto_pc_0 || ORIG_REF_NAME==axi_gpio_eg_auto_pc_0} -quiet] -quiet

# IP: bd/axi_gpio_eg/ip/axi_gpio_eg_axi_gpio_1_0/axi_gpio_eg_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_eg_axi_gpio_1_0 || ORIG_REF_NAME==axi_gpio_eg_axi_gpio_1_0} -quiet] -quiet

# IP: bd/axi_gpio_eg/ip/axi_gpio_eg_axi_gpio_2_0/axi_gpio_eg_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_gpio_eg_axi_gpio_2_0 || ORIG_REF_NAME==axi_gpio_eg_axi_gpio_2_0} -quiet] -quiet

# XDC: c:/Users/eduar/Documents/GitHub/school/ece520l-system-on-chip-design-lab/axi_gpio_eg/axi_gpio_eg.gen/sources_1/bd/axi_gpio_eg/axi_gpio_eg_ooc.xdc
